### ISSUE TITLE
The description of this repo says "polymorphic" instead of "isomorphic" or "universal"

### ISSUE THREAD

**Issue by pajtai** [GianlucaGuarini/riot-app-example#5]
The description near the top of the page for https://github.com/GianlucaGuarini/riot-app-example reads `Simple riotjs polymorphic app`. It should be `isomorphic` or `universal`
![screen shot 2016-07-27 at 15 31 48](https://cloud.githubusercontent.com/assets/1643937/17194868/4b081d94-540f-11e6-96de-4ff17b69c090.png)

**Comment by GianlucaGuarini** [comment]
thanks fixed
